package modetype

import (
	"fmt"

	"github.com/edipermadi/music/pkg/theory/scale"
)

var mapScaleToTypes = map[scale.Scale]Types{
	// 3 Notes
	scale.Minoric: {Minoric},

	// 4 Notes
	scale.Thaptic:  {Thaptic, Lothic, Phratic, Aerathic},
	scale.Epathic:  {Epathic, Mynic, Rothic, Eporic},
	scale.Zyphic:   {Zyphic, Epogic, Lanic, Pyrric},
	scale.Aeoloric: {Aeoloric, Gonic, Dalic, Dygic},
	scale.Daric:    {Daric, Lonic, Phradic, Bolic},
	scale.Saric:    {Saric, Zoptic, Aeraphic, Byptic},
	scale.Aeolic:   {Aeolic, Koptic, Mixolyric, Lydic},
	scale.Stathic:  {Stathic, Dadic},
	scale.Phrynic:  {Phrynic},

	// 5 Notes
	scale.Epathitonic:   {Epathitonic, Mynitonic, Rocritonic, Pentatonic, Thaptitonic},
	scale.Magitonic:     {Magitonic, Daditonic, Aeolyphritonic, Gycritonic, Pyritonic},
	scale.Gathitonic:    {Gathitonic, Ionitonic, Phrynitonic, Stathitonic, Thalitonic},
	scale.Zolitonic:     {Zolitonic, Epogitonic, Lanitonic, Paptitonic, Ionacritonic},
	scale.Phraditonic:   {Phraditonic, Aeoloritonic, Gonitonic, Dalitonic, Dygitonic},
	scale.Aeracritonic:  {Aeracritonic, Byptitonic, Daritonic, Lonitonic, Ionycritonic},
	scale.Lothitonic:    {Lothitonic, Phratonic, Aerathitonic, Saritonic, Zoptitonic},
	scale.Dolitonic:     {Dolitonic, Poritonic, Aerylitonic, Zagitonic, Lagitonic},
	scale.Molitonic:     {Molitonic, Staptitonic, Mothitonic, Aeritonic, Ragitonic},
	scale.Ionaditonic:   {Ionaditonic, Bocritonic, Gythitonic, Pagitonic, Aeolythitonic},
	scale.Zacritonic:    {Zacritonic, Laritonic, Thacritonic, Styditonic, Loritonic},
	scale.Aeolyritonic:  {Aeolyritonic, Goritonic, Aeoloditonic, Doptitonic, Aeraphitonic},
	scale.Zathitonic:    {Zathitonic, Raditonic, Stonitonic, Syptitonic, Ionythitonic},
	scale.Aeolanitonic:  {Aeolanitonic, Danitonic, Ionaritonic, Dynitonic, Zyditonic},
	scale.Aeolacritonic: {Aeolacritonic, Zythitonic, Dyritonic, Koptitonic, Thocritonic},
	scale.Lycritonic:    {Lycritonic, Daptitonic, Kygitonic, Mocritonic, Zynitonic},
	scale.Epygitonic:    {Epygitonic, Zaptitonic, Kagitonic, Zogitonic, Epyritonic},
	scale.Zothitonic:    {Zothitonic, Phrolitonic, Ionagitonic, Aeolapritonic, Kyritonic},
	scale.Ionyptitonic:  {Ionyptitonic, Gyritonic, Zalitonic, Stolitonic, Bylitonic},
	scale.Thoditonic:    {Thoditonic, Dogitonic, Phralitonic, Garitonic, Soptitonic},
	scale.Kataritonic:   {Kataritonic, Sylitonic, Thonitonic, Phropitonic, Staditonic},
	scale.Lyditonic:     {Lyditonic, Mythitonic, Sogitonic, Gothitonic, Rothitonic},
	scale.Zylitonic:     {Zylitonic, Zoditonic, Zaritonic, Phrythitonic, Rolitonic},
	scale.Ranitonic:     {Ranitonic, Laditonic, Poditonic, Ionothitonic, Kanitonic},
	scale.Ryphitonic:    {Ryphitonic, Gylitonic, Aeolycritonic, Pynitonic, Zanitonic},
	scale.Phronitonic:   {Phronitonic, Banitonic, Aeronitonic, Golitonic, Dyptitonic},
	scale.Aerynitonic:   {Aerynitonic, Palitonic, Stothitonic, Aerophitonic, Katagitonic},
	scale.Ionoditonic:   {Ionoditonic, Bogitonic, Mogitonic, Docritonic, Epaditonic},
	scale.Mixitonic:     {Mixitonic, Phrothitonic, Katycritonic, Ionalitonic, Loptitonic},
	scale.Thyritonic:    {Thyritonic, Thoptitonic, Bycritonic, Pathitonic, Myditonic},
	scale.Bolitonic:     {Bolitonic, Bothitonic, Kataditonic, Koditonic, Tholitonic},

	// 6 Notes
	scale.Epathimic:  {Epathimic, Mynimic, Rocrimic, Eporimic, Thaptimic, Lothimic},
	scale.Dyrimic:    {Dyrimic, Koptimic, Thocrimic, Aeolanimic, Danimic, Ionarimic},
	scale.Daptimic:   {Daptimic, Kygimic, Mocrimic, Zynimic, Aeolimic, Zythimic},
	scale.Epygimic:   {Epygimic, Zaptimic, Kagimic, Zogimic, Epyrimic, Lycrimic},
	scale.Bylimic:    {Bylimic, Zothimic, Phrolimic, Ionagimic, Aeolaphimic, Kycrimic},
	scale.Garimic:    {Garimic, Soptimic, Ionyptimic, Gyrimic, Zalimic, Stolimic},
	scale.Thonimic:   {Thonimic, Stadimic, Thodimic},
	scale.Mythimic:   {Mythimic, Sogimic, Gogimic, Rothimic, Katarimic, Sylimic},
	scale.Mixolimic:  {Mixolimic, Dadimic, Aeolyphimic, Gycrimic, Pyrimic, Lydimic},
	scale.Ionacrimic: {Ionacrimic, Gathimic, Ionynimic, Phrynimic, Stathimic, Thatimic},
	scale.Dalimic:    {Dalimic, Dygimic, Zolimic, Epogimic, Lanimic, Paptimic},
	scale.Darmic:     {Darmic, Lonimic, Ionycrimic, Phradimic, Aeolorimic, Gonimic},
	scale.Phracrimic: {Phracrimic, Aerathimic, Sarimic, Zoptimic, Zeracrimic, Byptimic},
	scale.Starimic:   {Starimic, Phrathimic, Saptimic, Aerodimic, Macrimic, Rogimic},
	scale.Bygimic:    {Bygimic, Thycrimic, Aeoladimic, Dylimic, Eponimic, Katygimic},
	scale.Stalimic:   {Stalimic, Stoptimic, Zygimic, Kataptimic, Aeolaptimic, Pothimic},
	scale.Rycrimic:   {Rycrimic, Ronimic, Stycrimic, Katorimic, Epythimic, Kaptimic},
	scale.Katythimic: {Katythimic, Madimic, Aerygimic, Pylimic, Ionathimic, Morimic},
	scale.Aerycrimic: {Aerycrimic, Ganimic, Eparimic, Lyrimic, Phraptimic, Bacrimic},
	scale.Phralimic:  {Phralimic, Phrogimic, Rathimic, Katocrimic, Phryptimic, Katynimic},
	scale.Solimic:    {Solimic, Ionolimic, Ionophimic, Aeologimic, Zadimic, Sygimic},
	scale.Thogimic:   {Thogimic, Rythimic, Donimic, Aeoloptimic, Panimic, Lodimic},
	scale.Laptimic:   {Laptimic, Lygimic, Logimic, Lalimic, Sothimic, Phrocrimic},
	scale.Modimic:    {Modimic, Barimic, Poptimic, Sagimic, Aelothimic, Socrimic},
	scale.Syrimic:    {Syrimic, Stodimic, Ionocrimic, Zycrimic, Ionygimic, Katathimic},
	scale.Bolimic:    {Bolimic, Bothimic, Katadimic, Kodimic, Tholimic, Ralimic},
	scale.Kanimic:    {Kanimic, Zylimic, Zodimic, Zarimic, Phrythimic, Rorimic},
	scale.Pynimic:    {Pynimic, Zanimic, Ranimic, Ladimic, Podimic, Ionothimic},
	scale.Kytrimic:   {Kytrimic, Golimic, Dyptimic, Ryrimic, Gylimic, Aeolycrimic},
	scale.Palimic:    {Palimic, Stothimic, Aeronimic, Katagimic, Phronimic, Banimic},
	scale.Ionodimic:  {Ionodimic, Bogimic, Mogimic, Docrimic, Epadimic, Aerynimic},
	scale.Mydimic:    {Mydimic, Thyptimic, Phrothimic, Katycrimic, Ionalimic, Loptimic},
	scale.Zagimic:    {Zagimic, Lagimic, Thyrimic, Thothimic, Bycrimic, Pathimic},
	scale.Mothimic:   {Mothimic, Aeranimic, Ragimic, Dolimic, Porimic, Aerylimic},
	scale.Bocrimic:   {Bocrimic, Gythimic, Pagimic, Aeolythimic, Molimic, Staptimic},
	scale.Zacrimic:   {Zacrimic, Larimic, Thacrimic, Stydimic, Lorimic, Ionadimic},
	scale.Ionythimic: {Ionythimic, Aerythimic},
	scale.Dynimic:    {Dynimic, Zydimic, Zathimic, Radimic, Stonimic, Syptimic},
	scale.Ponimic:    {Ponimic, Kadimic, Gynimic, Thydimic, Polimic, Thanimic},
	scale.Lathimic:   {Lathimic, Aeralimic, Kynimic, Stynimic, Epytimic, Katoptimic},
	scale.Galimic:    {Galimic, Kathimic, Lylimic, Epalimic, Epacrimic, Sathimic},
	scale.Katanimic:  {Katanimic, Katyrimic, Rynimic, Pogimic, Aeraptimic, Epylimic},
	scale.Manimic:    {Manimic, Marimic, Locrimic, Rylimic, Epatimic, Byrimic},
	scale.Kocrimic:   {Kocrimic, Korimic, Lynimic, Malimic, Synimic, Phragimic},
	scale.Mycrimic:   {Mycrimic, Ionorimic, Phrydimic, Zyptimic, Katothimic, Phrylimic},
	scale.Aerothimic: {Aerothimic, Stagimic, Dorimic, Phrycrimic, Kyptimic, Ionylimic},
	scale.Epynimic:   {Epynimic, Ionogimic, Kydimic, Gaptimic, Tharimic, Ionaphimic},
	scale.Thoptimic:  {Thoptimic, Bagimic, Kyrimic, Sonimic, Aeolonimic, Rygimic},
	scale.Thagimic:   {Thagimic, Kolimic, Dycrimic, Epycrimic, Gocrimic, Katolimic},
	scale.Dagimic:    {Dagimic, Aeolydimic, Parimic, Ionaptimic, Thylimic, Lolimic},
	scale.Thalimic:   {Thalimic, Stygimic, Aeolygimic, Aerogimic, Dacrimic, Baptimic},
	scale.Stythimic:  {Stythimic, Kothimic, Pygimic, Rodimic, Sorimic, Monimic},
	scale.Aeragimic:  {Aeragimic, Epothimic, Salimic, Lyptimic, Katonimic, Gygimic},
	scale.Aeradimic:  {Aeradimic, Zyrimic, Stylimic},
	scale.Lythimic:   {Lythimic, Dodimic, Katalimic},
	scale.Boptimic:   {Boptimic, Stogimic, Thynimic, Aeolathimic, Bythimic, Padimic},
	scale.Dathimic:   {Dathimic, Epagimic, Raptimic, Epolimic, Sythimic, Sydimic},
	scale.Gacrimic:   {Gacrimic, Borimic, Sycrimic, Gadimic, Aeolocrimic, Phrygimic},
	scale.WholeTone:  {WholeTone},

	// 7 Notes
	scale.Lydian:     {Lydian, Mixolydian, Aeolian, Locrian, Ionian, Dorian, Phrygian},
	scale.Ionythian:  {Ionythian, Aeolyrian, Gorian, Aeolodian, Doptian, Aeraphian, Zacrian},
	scale.Ionarian:   {Ionarian, Dynian, Zydian, Zathian, Radian, Stonian, Syptian},
	scale.Aeolacrian: {Aeolacrian, Zythian, Dyrian, Koptian, Thocrian, Aeolanian, Danian},
	scale.Zogian:     {Zogian, Epyrian, Lycrian, Daptian, Kygian, Mocrian, Zynian},
	scale.Phrolian:   {Phrolian, Ionagian, Aeodian, Kycrian, Epygian, Zaptian, Kagian},
	scale.Soptian:    {Soptian, Ionyptian, Gyrian, Zalian, Stolian, Bylian, Zothian},
	scale.Thonian:    {Thonian, Phrorian, Stadian, Thodian, Dogian, Mixopyrian, Garian},
	scale.Epathian:   {Epathian, Mythian, Sogian, Gogian, Rothian, Katarian, Stylian},
	scale.Stathian:   {Stathian, Mixonyphian, Magian, Dadian, Aeolylian, Gycrian, Pyrian},
	scale.Epogian:    {Epogian, Lanian, Paptian, Ionacrian, Gathian, Ionyphian, Phrynian},
	scale.Ionycrian:  {Ionycrian, Phradian, Aeolorian, Gonian, Dalian, Dygian, Zolian},
	scale.Aerathian:  {Aerathian, Sarian, Zoptian, Aeracrian, Byptian, Darian, Lonian},
	scale.Aeopian:    {Aeopian, Rygian, Epynian, Ionogian, Kydian, Gaptian, Tharian},
	scale.Epycrian:   {Epycrian, Gocrian, Katolian, Thoptian, Bagian, Kyrian, Sonian},
	scale.Parian:     {Parian, Ionaptian, Thylian, Lolian, Thagian, Kolian, Dycrian},
	scale.Stygian:    {Stygian, Aeolygian, Aerogian, Dacrian, Baptian, Dagian, Aeolydian},
	scale.Stythian:   {Stythian, Kothian, Pygian, Rodian, Sorian, Monian, Thalian},
	scale.Zorian:     {Zorian, Aeragian, Epothian, Salian, Lyptian, Katonian, Gyphian},
	scale.Thacrian:   {Thacrian, Dodian, Aeolyptian, Aeolonian, Aeradian, Aeolagian, Zyrian},
	scale.Aeolathian: {Aeolathian, Bythian, Padian, Rolian, Pydian, Thygian, Katalian},
	scale.Saptian:    {Saptian, Aerodian, Macrian, Rogian, Boptian, Stogian, Thynian},
	scale.Thycrian:   {Thycrian, Aeoladian, Dylian, Eponian, Katygian, Starian, Phrathian},
	scale.Stalian:    {Stalian, Stoptian, Zygian, Kataptian, Aeolaptian, Pothian, Bygian},
	scale.Morian:     {Morian, Rycrian, Ronian, Stycrian, Katorian, Epythian, Kaptian},
	scale.Phraptian:  {Phraptian, Bacrian, Katythian, Madian, Aerygian, Pylian, Ionathian},
	scale.Katocrian:  {Katocrian, Phryptian, Katynian, Aerycrian, Ganian, Eparian, Lyrian},
	scale.Ionopian:   {Ionopian, Aeologian, Zadian, Sygian, Phralian, Phrogian, Rathian},
	scale.Rythian:    {Rythian, Donian, Aeoloptian, Panian, Lodian, Solian, Ionolian},
	scale.Laptian:    {Laptian, Lygian, Logian, Lalian, Sothian, Phrocrian, Thogian},
	scale.Katathian:  {Katathian, Modian, Barian, Mixolocrian, Sagian, Aeolothian, Socrian},
	scale.Tholian:    {Tholian, Ralian, Syrian, Stodian, Ionocrian, Zycrian, Ionygian},
	scale.Zarian:     {Zarian, Phrythian, Rorian, Bolian, Bothian, Katadian, Kodian},
	scale.Ranian:     {Ranian, Ladian, Podian, Ionothian, Kanian, Zylian, Zodian},
	scale.Golian:     {Golian, Dyptian, Ryphian, Gylian, Aeolycrian, Pynian, Zanian},
	scale.Palian:     {Palian, Stothian, Aerorian, Katagian, Phronian, Banian, Aeronian},
	scale.Loptian:    {Loptian, Ionodian, Bogian, Mogian, Docrian, Epadian, Aerynian},
	scale.Bycrian:    {Bycrian, Pathian, Mydian, Thyptian, Phrothian, Katycrian, Ionalian},
	scale.Dolian:     {Dolian, Porian, Aerylian, Zagian, Lagian, Tyrian, Mixonorian},
	scale.Pagian:     {Pagian, Aeolythian, Molian, Staptian, Mothian, Aeranian, Ragian},
	scale.Larian:     {Larian, Lythian, Stydian, Lorian, Ionadian, Bocrian, Mixolythian},
	scale.Thadian:    {Thadian, Sanian, Ionydian, Epydian, Katydian, Mathian, Aeryptian},
	scale.Pythian:    {Pythian, Katylian, Bydian, Bynian, Galian, Zonian, Myrian},
	scale.Katogian:   {Katogian, Stacrian, Styrian, Ionyrian, Phrodian, Pycrian, Gyptian},
	scale.Katacrian:  {Katacrian, Sodian, Bathian, Mylian, Godian, Thorian, Zocrian},
	scale.Stanian:    {Stanian, Epanian, Konian, Stocrian, Kalian, Phroptian, Dydian},
	scale.Katyptian:  {Katyptian, Epodian, Mygian, Pacrian, Aerocrian, Aeolarian, Kythian},
	scale.Bonian:     {Bonian, Badian, Katodian, Sadian, Dothian, Moptian, Aeryrian},
	scale.Epagian:    {Epagian, Raptian, Epolian, Sythian, Sydian, Epocrian, Kylian},
	scale.Gacrian:    {Gacrian, Borian, Sycrian, Gadian, Aeolocrian, Mixodorian, Dathian},
	scale.Katoptian:  {Katoptian, Ponian, Kadian, Gynian, Thyphian, Polian, Thanian},
	scale.Epacrian:   {Epacrian, Sathian, Lathian, Aeralian, Kynian, Stynian, Epyphian},
	scale.Pogian:     {Pogian, Aeraptian, Epylian, Gamian, Kathian, Lylian, Epalian},
	scale.Eporian:    {Eporian, Rylian, Epaptian, Byrian, Katanian, Katyrian, Rynian},
	scale.Korian:     {Korian, Lynian, Malian, Synian, Phragian, Manian, Marian},
	scale.Mycrian:    {Mycrian, Ionorian, Phrydian, Zyptian, Katothian, Phrylian, Kocrian},
	scale.Ionanian:   {Ionanian, Aerothian, Stagian, Lothian, Phrycrian, Kyptian, Ionylian},
	scale.Gydian:     {Gydian, Kogian, Rarian, Aerolian, Karian, Myptian, Rydian},
	scale.Aeolynian:  {Aeolynian, Aeroptian, Phryrian, Gothian, Storian, Pyptian, Thydian},

	// 8 Notes
	scale.Aerycryllic:     {Aerycryllic, Gadyllic, Solyllic, Zylyllic, Mixodyllic, Soryllic, Godyllic, Epiphyllic},
	scale.Pynyllic:        {Pynyllic, Bocryllic, Kogyllic, Raryllic, Zycryllic, Mycryllic, Laptyllic, Pylyllic},
	scale.Pothyllic:       {Pothyllic, Phronyllic, Stynyllic, Rathyllic, Aeryptyllic, Zydyllic, Katolyllic, Rythyllic},
	scale.Locryllic:       {Locryllic, Bylyllic, Sogyllic, Ionycryllic, Koptyllic, Epyryllic, Soptyllic, Aeolylyllic},
	scale.Aeracryllic:     {Aeracryllic, Epygyllic, Thonyllic, Lanyllic, Phrynyllic, Lycryllic, Ionyptyllic, Epathyllic},
	scale.Dydyllic:        {Dydyllic, Thogyllic, Rygyllic, Bycryllic, Zacryllic, Panyllic, Dyryllic, Zathyllic},
	scale.Dagyllic:        {Dagyllic, Katalyllic, Katoryllic, Dodyllic, Zogyllic, Madyllic, Dycryllic, Aeologyllic},
	scale.Sydyllic:        {Sydyllic, Katogyllic, Zygyllic, Aeralyllic},
	scale.Bacryllic:       {Bacryllic, Aerygyllic, Dathyllic, Boptyllic, Bagyllic, Mathyllic, Styptyllic, Zolyllic},
	scale.Rocryllic:       {Rocryllic, Zyryllic, Sagyllic, Epinyllic, Katagyllic, Ragyllic, Gothyllic, Lythyllic},
	scale.Ionocryllic:     {Ionocryllic, Gocryllic, Epiryllic, Aeradyllic, Staptyllic, Danyllic, Goptyllic, Epocryllic},
	scale.Ionoptyllic:     {Ionoptyllic, Aeoloryllic, Thydyllic, Gycryllic, Lyryllic, Mogyllic, Katodyllic, Moptyllic},
	scale.Dolyllic:        {Dolyllic, Moryllic, Bydyllic, Pocryllic, Phracryllic, Gyryllic, Phrygyllic, Dogyllic},
	scale.Thagyllic:       {Thagyllic, Thoptyllic, Phraptyllic, Gylyllic, Phralyllic, Dygyllic, Ronyllic, Epogyllic},
	scale.Aeoladyllic:     {Aeoladyllic, Kocryllic, Lodyllic, Bynyllic, Kydyllic, Bygyllic, Phryptyllic, Ionayllic},
	scale.Phroryllic:      {Phroryllic, Thyphyllic, Poptyllic, Mixonyllic, Paptyllic, Storyllic, Phrycryllic, Palyllic},
	scale.Phranyllic:      {Phranyllic, Stydyllic, Zadyllic, Zalyllic, Zocryllic, Katocryllic, Aerathyllic, Stoptyllic},
	scale.Lydyllic:        {Lydyllic, Radyllic, Stagyllic, Ionoryllic, Phrodyllic, Aeragyllic, Banyllic, Epothyllic},
	scale.Zoryllic:        {Zoryllic, Phrolyllic, Kolyllic, Thodyllic, Socryllic, Aeolyllic, Zythyllic, Aeoryllic},
	scale.Mixolydyllic:    {Mixolydyllic, Mixonyphyllic, Aeolanyllic, Thocryllic, Kygyllic, Ionagyllic, Gogyllic, Phradyllic},
	scale.Ioniptyllic:     {Ioniptyllic, Kycryllic, Aeolaptyllic, Rodyllic, Ionathyllic, Pythyllic, Zonyllic, Ryryllic},
	scale.Aeolothyllic:    {Aeolothyllic, Ionyryllic, Rydyllic, Gonyllic, Rolyllic, Katydyllic, Zyptyllic, Modyllic},
	scale.Maptyllic:       {Maptyllic, Aeraptyllic, Katadyllic, Magyllic, Phrylyllic, Epigyllic, Molyllic, Ponyllic},
	scale.Thyptyllic:      {Thyptyllic, Ionogyllic, Aeolaryllic, Katygyllic, Ganyllic, Kyptyllic, Salyllic, Sanyllic},
	scale.Doptyllic:       {Doptyllic, Ionilyllic, Manyllic, Polyllic, Stanyllic, Mixotharyllic, Eporyllic, Aerynyllic},
	scale.Lonyllic:        {Lonyllic, Sathyllic, Layllic, Saryllic, Thacryllic, Aeolynyllic, Thadyllic, Lynyllic},
	scale.Aeolathyllic:    {Aeolathyllic, Aeolocryllic, Phroptyllic, Kodyllic, Epaptyllic, Ionoyllic, Gyptyllic, Aerythyllic},
	scale.Zagyllic:        {Zagyllic, Epacryllic, Thorcryllic, Loptyllic, Katylyllic, Malyllic, Mydyllic, Thycryllic},
	scale.Gythyllic:       {Gythyllic, Pyryllic, Rycryllic, Phrathyllic, Badyllic, Phrocryllic, Staryllic, Zothyllic},
	scale.Tharyllic:       {Tharyllic, Sylyllic, Lothyllic, Daryllic, Monyllic, Styryllic, Aeolacryllic, Raptyllic},
	scale.Kataryllic:      {Kataryllic, Aerocryllic, Zanyllic, Aeolonyllic, Aeonyllic, Kyryllic, Sythyllic, Katycryllic},
	scale.Stogyllic:       {Stogyllic, Ionidyllic, Stonyllic, Stalyllic, Poryllic, Mocryllic, Aeolyryllic, Baryllic},
	scale.Dalyllic:        {Dalyllic, Ionyphyllic, Zaptyllic, Garyllic, Gathyllic, Mixopyryllic, Ionacryllic, Stylyllic},
	scale.Stycryllic:      {Stycryllic, Ionothyllic, Mythyllic, Aerylyllic, Bonyllic, Tholyllic, Katyryllic, Sadyllic},
	scale.Stolyllic:       {Stolyllic, Logyllic, Dacryllic, Thynyllic, Gydyllic, Eparyllic, Dynyllic, Ionyllic},
	scale.Zaryllic:        {Zaryllic, Dythyllic, Ionaryllic, Laryllic, Kataptyllic, Sonyllic, Pathyllic, Loryllic},
	scale.Aeronyllic:      {Aeronyllic, Pycryllic, Mygyllic, Lylyllic, Daptyllic, Ioninyllic, Epaphyllic, Lolyllic},
	scale.Stacryllic:      {Stacryllic, Doryllic, Kadyllic, Rynyllic, Aerogyllic, Rothyllic, Kagyllic, Stathyllic},
	scale.Thyryllic:       {Thyryllic, Gygyllic, Sodyllic, Goryllic, Bothyllic, Gynyllic, Ionaptyllic, Phryryllic},
	scale.Racryllic:       {Racryllic, Epicryllic, Stygyllic, Syryllic, Stythyllic, Aerothyllic, Mixoryllic, Thanyllic},
	scale.Epotyllic:       {Epotyllic, Epidyllic, Kaptyllic},
	scale.MajorDiminished: {MajorDiminished, MinorDiminished},

	// 9 Notes
	scale.Aerycrygic:  {Aerycrygic, Gadygic, Solygic, Zylygic, Garygic, Sorygic, Godygic, Epithygic, Ionoptygic},
	scale.Kalygic:     {Kalygic, Ionodygic, Bythygic, Epygic, Marygic, Gaptygic, Aeroptygic, Mylygic, Galygic},
	scale.Mixolydygic: {Mixolydygic, Ionycrygic, Zoptygic, Phrygygic, Locrygic, Gonygic, Aeracrygic, Aerathygic, Dorygic},
	scale.Dycrygic:    {Dycrygic, Aeolygic, Dydygic, Tholygic, Rynygic, Bycrygic, Zacrygic, Panygic, Dyrygic},
	scale.Loptygic:    {Loptygic, Katylygic, Phradygic, Mixodygic, Katalygic, Katorygic, Dogygic, Zodygic, Madygic},
	scale.Bagygic:     {Bagygic, Mathygic, Styptygic, Zolygic, Sydygic, Katygic, Zyphygic, Aeralygic, Ryptygic},
	scale.Apinygic:    {Apinygic, Katagygic, Radygic, Gothygic, Lythygic, Bacrygic, Aerygic, Dathygic, Boptygic},
	scale.Epyrygic:    {Epyrygic, Aeradygic, Staptygic, Danygic, Goptygic, Epocrygic, Rocrygic, Zyrygic, Sadygic},
	scale.Aeolorygic:  {Aeolorygic, Thydygic, Gycrygic, Lyrygic, Modygic, Katodygic, Moptygic, Ionocrygic, Gocrygic},
	scale.Manygic:     {Manygic, Polygic, Stanygic, Thaptygic, Eporygic, Aerynygic, Thyptygic, Ionogygic, Aeolarygic},
	scale.Sathygic:    {Sathygic, Ladygic, Sarygic, Thacrygic, Aeolynygic, Thadygic, Lynygic, Doptygic, Ionilygic},
	scale.Phrygic:     {Phrygic, Aeranygic, Dothygic, Lydygic, Stadygic, Byptygic, Stodygic, Zynygic, Lonygic},
	scale.Zothygic:    {Zothygic, Aeolathygic, Aeolocrygic, Phroptygic, Kodygic, Eparygic, Ionygic, Gyptygic, Aerythygic},
	scale.Aeolacrygic: {Aeolacrygic, Raptygic, Gythygic, Pyrygic, Rycrygic, Phrathygic, Badygic, Phrocrygic, Starygic},
	scale.Kyrygic:     {Kyrygic, Sythygic, Katycrygic, Tharygic, Sylygic, Lothygic, Darygic, Monygic, Styrygic},
	scale.Porygic:     {Porygic, Mocrygic, Aeolyrygic, Barygic, Katarygic, Aerocrygic, Zanygic, Aeolonygic, Aeolanygic},
	scale.Kaptygic:    {Kaptygic, Sacrygic, Padygic, Epilygic, Kynygic, Stophygic, Ionidygic, Stonygic, Stalygic},
	scale.Koptygic:    {Koptygic, Raphygic, Zycrygic, Mycrygic, Laptygic, Pylygic, Rodygic, Epolygic, Epidygic},
	scale.Phronygic:   {Phronygic, Stynygic, Zydygic},

	// 10 notes
	scale.Aerycryllian: {Aerycryllian, Gadyllian, Solyllian, Zyphyllian, Garyllian, Soryllian, Godyllian, Epityllian, Ionyllian, Aeoryllian},
	scale.Katoryllian:  {Katoryllian, Dodyllian, Zogyllian, Madyllian, Dycryllian, Aeogyllian, Dydyllian, Thogyllian, Rygyllian, Bathyllian},
	scale.Sydyllian:    {Sydyllian, Katogyllian, Mixodyllian, Aeradyllian, Ryptyllian, Loptyllian, Kataphyllian, Phradyllian, Dagyllian, Katyllian},
	scale.Gothyllian:   {Gothyllian, Lythyllian, Bacryllian, Aerygyllian, Dathyllian, Boptyllian, Bagyllian, Mathyllian, Styptyllian, Zolyllian},
	scale.Staptyllian:  {Staptyllian, Danyllian, Goptyllian, Epocryllian, Rocryllian, Zyryllian, Sagyllian, Epinyllian, Katagyllian, Ragyllian},
	scale.Thydyllian:   {Thydyllian, Epiryllian, Lyryllian, Mogyllian, Katodyllian},

	// 11 notes
	scale.Aerycratic: {Aerycratic, Monatic, Solatic, Zylatic, Mixolatic, Soratic, Godatic, Eptatic, Ionatic, Aeolatic, Thydatic},

	// 12 notes
	scale.Chromatic: {Chromatic},
}

// Scale return scale of a mode
func (t Type) Scale() (scale.Scale, int) {
	for givenScale, givenModes := range mapScaleToTypes {
		for i, givenMode := range givenModes {
			if givenMode == t {
				return givenScale, i + 1
			}
		}
	}

	panic(fmt.Errorf("no such scale for mode %s", t))
}

// AllModesInScale return modes in given scale, sorted ascending by numbering
func AllModesInScale(givenScale scale.Scale) Types {
	if v, found := mapScaleToTypes[givenScale]; found {
		return v
	}

	panic(fmt.Errorf("no such modes in scale %s", givenScale))
}
